logLevel="DEBUG"

################################################################
# API
################################################################

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
  
################################################################
# Metrics
################################################################

[entryPoints]
  [entryPoints.http]
    address = ":8000"

################################################################
# Metrics
################################################################

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]

################################################################
# Docker Provider
################################################################

[docker]
  endpoint = "unix:///var/run/docker.sock"
  #endpoint = "tcp://socat:2375"
  watch = true
  swarmMode = false
  exposedByDefault = false
  domain = "docker.local"
