scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  dns_sd_configs:
  - names:
    - 'tasks.cadvisor'
    type: 'A'
    port: 8080
- job_name: traefik
  scrape_interval: 5s
  dns_sd_configs:
  - names:
    - 'tasks.traefik'
    type: 'A'
    port: 8080
- job_name: node
  scrape_interval: 5s
  dns_sd_configs:
  - names:
    - 'tasks.node-exporter'
    type: 'A'
    port: 9100
- job_name: docker
  scrape_interval: 5s
  static_configs:
  - targets: ["192.168.99.100:9323","192.168.99.101:9323","192.168.99.102:9323"]