logLevel = "DEBUG"

################################################################
# API
################################################################

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
  
################################################################
# Metrics
################################################################

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]

################################################################
# Docker Provider
################################################################

[docker]
  endpoint = "tcp://socat:2375"
#  endpoint = "/var/run/docker.sock"
  watch = true
  swarmMode = false
  exposedByDefault = false
  usebindportip = true

################################################################
# Entrypoints
################################################################

[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.traefik]
  address = ":9443"
  [entryPoints.https]
  address = ":443"
  insecureSkipVerify = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/certs/selfsigned.crt"
        keyFile = "/certs/selfsigned.key"

# [[tls]]
#   entryPoints = ["https"]
#   [tls.certificate]
#     certFile = "/certs/cert.crt"
#     keyFile = "/certs/cert.key"